services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  streamlit:
      build:
        # context: ./webapp
        dockerfile: ./webapp/Dockerfile
      ports:
        - "8501:8501"
      volumes:
        - ./webapp:/app
        - ./src:/src
        - ./models:/models
        - ./data:/data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        - postgres

volumes:
  pgdata:
