FROM python:3.9-slim

RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install odbcinst -y
RUN apt-get install unixodbc -y
RUN apt-get install wget -y

ENV ACCEPT_EULA=Y

RUN wget https://packages.microsoft.com/debian/12/prod/pool/main/m/msodbcsql18/msodbcsql18_18.4.1.1-1_arm64.deb
RUN dpkg -i msodbcsql18_18.4.1.1-1_arm64.deb

RUN apt-get update --allow-unauthenticated

WORKDIR /app
COPY ./webapp/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src /src
WORKDIR /src

RUN pip install --prefer-binary -e .

COPY . .

WORKDIR /app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
